### PR TITLE
Wrapped portals GP models to allow pandas input

### PR DESCRIPTION
**Pull request by aaronkho**
- Created new class: `wrapped_models_portals` (replaces `simple_model_portals`)
- Accepts nested `list`, `numpy.ndarray`, `pandas.DataFrame` as inputs
- Using `pandas.DataFrame` allows flexible variable order in input data
- Currently returns all outputs, unless specific targets are given through evaluation call
- Added `generateScan()` function which creates single variable scans around a given training point of a given model

### CODE REVIEW

**Comment by aaronkho** [comment]
Result of testing:
```
Python 3.9.4 (default, Apr 16 2021, 15:57:27)
Type 'copyright', 'credits' or 'license' for more information
IPython 8.18.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import numpy as np, pandas as pd

In [2]: from mitim_modules.portals.utils import PORTALSanalysis
  > PyQt6 module or backends could not be loaded by MITIM, notebooks will not work but I let you continue

In [3]: pobj = PORTALSanalysis.PORTALSanalyzer.from_folder('portals_test/')

...Opening PORTALS class from folder portals_test/
 - Parent opt_evaluator function initialized
        - Folder: portals_test/
        - No namelist provided (likely b/c for reading/plotting purposes)
                --> Opening optimization_object.pkl
 - Parent opt_evaluator function initialized
        - Folder: None
        - No namelist provided (likely b/c for reading/plotting purposes)
 - Reading pickle file with optimization_object class
        * Read ...ls_test//Outputs/optimization_object.pkl state file, grabbed step #-1
                        - Time stamp of optimization_object.pkl: 2024-08-29 19:09:14
                --> Opening ...s_test//Outputs/optimization_results.out

************************************
 * Initializing PORTALS analyzer...
 ************************************
 - Grabbing model
 - Interpreting PORTALS results
        - Reading profiles and tgyros for each evaluation
                - Could not read next profile to evaluate (from folder)
        - Processing metrics
                - Processing evaluation 0/2
                - Processing evaluation 1/2
                - Processing evaluation 2/2

In [4]: model = pobj.extractModels()

****************************************************************************************************
> MITIM has extracted 36 GP models as a dictionary (only returned variable), to proceed:
    1. Look at the dictionary keys to see which models are available:
                models.keys()
    2. Select one model and print its information (e.g. variable labels and order):
                m = models['QeTurb_1']
                m.printInfo()
    3. Trained points are stored as m.x, m.y, m.yvar, and you can make predictions with:
                x_test = m.x
                mean, upper, lower = m(x_test)
    4. Extract samples from the GP with:
                x_test = m.x
                samples = m(x_test,samples=100)
****************************************************************************************************


In [5]: rng = np.random.default_rng()

In [6]: df_in = pd.DataFrame(data={var: rng.random(10) for var in model.input_variables})

In [7]: df_out = model(df_in)

In [8]: df_out_one = model(df_in, outputs=['QeTurb_1'])

In [9]: df_out_some = model(df_in, outputs=['QiTurb_1', 'GeNeo_4', 'QeTar_3'])

In [10]: df_some = pd.concat([df_in, df_out_some], axis=1)

In [11]: df_in
Out[11]:
       aLte      aLti      aLne      PeGB      PiGB      CeGB
0  0.257607  0.222645  0.471305  0.941198  0.543826  0.579522
1  0.976584  0.413771  0.009993  0.105068  0.185798  0.505206
2  0.570134  0.182405  0.914908  0.734685  0.638639  0.748022
3  0.652186  0.008064  0.239845  0.940886  0.574705  0.216192
4  0.796242  0.953736  0.274307  0.148604  0.676921  0.808118
5  0.567499  0.327267  0.159028  0.950208  0.416015  0.137564
6  0.228205  0.143436  0.257088  0.769510  0.696590  0.033418
7  0.922698  0.708231  0.491979  0.487305  0.653184  0.647319
8  0.162086  0.053364  0.264185  0.847655  0.764146  0.251648
9  0.699009  0.177936  0.887069  0.578979  0.993927  0.726453

In [12]: df_out
Out[12]:
   QeTurb_1  QeTurb_1_upper  QeTurb_1_lower   QeNeo_1  QeNeo_1_upper  ...  GeNeo_4_upper  GeNeo_4_lower       GeTar_4  GeTar_4_upper  GeTar_4_lower
0  1.794191        1.808469        1.779912  0.002359       0.002429  ...       0.002846      -0.001459 -3.068709e+07  -3.068709e+07  -3.068709e+07
1 -0.129831       -0.115553       -0.144110  0.000326       0.000395  ...       0.001152      -0.003153 -4.213922e+07  -4.213922e+07  -4.213922e+07
2  3.943676        3.957955        3.929398  0.004359       0.004428  ...       0.005766       0.001461 -4.721422e+06  -4.721422e+06  -4.721422e+06
3  1.593321        1.607600        1.579043  0.002035       0.002105  ...       0.001421      -0.002885 -8.667619e+07  -8.667619e+07  -8.667619e+07
4 -0.433044       -0.418766       -0.447323  0.000142       0.000212  ...       0.003632      -0.000673  4.539468e+06   4.539468e+06   4.539468e+06
5  0.437783        0.452061        0.423505  0.000974       0.001043  ...       0.001473      -0.002832 -9.879267e+07  -9.879267e+07  -9.879267e+07
6  1.070004        1.084282        1.055725  0.001655       0.001724  ...       0.001364      -0.002941 -1.148415e+08  -1.148415e+08  -1.148415e+08
7  1.144606        1.158884        1.130327  0.001611       0.001681  ...       0.004594       0.000289 -2.023964e+07  -2.023964e+07  -2.023964e+07
8  1.272820        1.287098        1.258541  0.001858       0.001928  ...       0.001164      -0.003141 -8.121237e+07  -8.121237e+07  -8.121237e+07
9  3.920591        3.934869        3.906312  0.004302       0.004371  ...       0.005719       0.001414 -8.045075e+06  -8.045075e+06  -8.045075e+06

[10 rows x 108 columns]

In [13]: df_out_one
Out[13]:
   QeTurb_1  QeTurb_1_upper  QeTurb_1_lower
0  1.794191        1.808469        1.779912
1 -0.129831       -0.115553       -0.144110
2  3.943676        3.957955        3.929398
3  1.593321        1.607600        1.579043
4 -0.433044       -0.418766       -0.447323
5  0.437783        0.452061        0.423505
6  1.070004        1.084282        1.055725
7  1.144606        1.158884        1.130327
8  1.272820        1.287098        1.258541
9  3.920591        3.934869        3.906312

In [14]: df_out_some
Out[14]:
    QeTar_3  QeTar_3_upper  QeTar_3_lower  QiTurb_1  QiTurb_1_upper  QiTurb_1_lower   GeNeo_4  GeNeo_4_upper  GeNeo_4_lower
0  0.941198       0.991468       0.890928  0.602848        0.606424        0.599271  0.000694       0.002846      -0.001459
1  0.105068       0.155338       0.054798 -0.041332       -0.037756       -0.044908 -0.001000       0.001152      -0.003153
2  0.734685       0.784955       0.684415  1.309651        1.313228        1.306075  0.003614       0.005766       0.001461
3  0.940886       0.991156       0.890616  0.528936        0.532512        0.525359 -0.000732       0.001421      -0.002885
4  0.148604       0.198874       0.098334 -0.133648       -0.130072       -0.137225  0.001479       0.003632      -0.000673
5  0.950208       1.000477       0.899938  0.150986        0.154563        0.147410 -0.000679       0.001473      -0.002832
6  0.769510       0.819780       0.719240  0.362748        0.366324        0.359171 -0.000788       0.001364      -0.002941
7  0.487305       0.537575       0.437035  0.384214        0.387790        0.380638  0.002442       0.004594       0.000289
8  0.847655       0.897925       0.797385  0.429793        0.433369        0.426216 -0.000989       0.001164      -0.003141
9  0.578979       0.629249       0.528709  1.300269        1.303846        1.296693  0.003566       0.005719       0.001414

In [15]: df_some
Out[15]:
       aLte      aLti      aLne      PeGB      PiGB      CeGB  ...  QiTurb_1  QiTurb_1_upper  QiTurb_1_lower   GeNeo_4  GeNeo_4_upper  GeNeo_4_lower
0  0.257607  0.222645  0.471305  0.941198  0.543826  0.579522  ...  0.602848        0.606424        0.599271  0.000694       0.002846      -0.001459
1  0.976584  0.413771  0.009993  0.105068  0.185798  0.505206  ... -0.041332       -0.037756       -0.044908 -0.001000       0.001152      -0.003153
2  0.570134  0.182405  0.914908  0.734685  0.638639  0.748022  ...  1.309651        1.313228        1.306075  0.003614       0.005766       0.001461
3  0.652186  0.008064  0.239845  0.940886  0.574705  0.216192  ...  0.528936        0.532512        0.525359 -0.000732       0.001421      -0.002885
4  0.796242  0.953736  0.274307  0.148604  0.676921  0.808118  ... -0.133648       -0.130072       -0.137225  0.001479       0.003632      -0.000673
5  0.567499  0.327267  0.159028  0.950208  0.416015  0.137564  ...  0.150986        0.154563        0.147410 -0.000679       0.001473      -0.002832
6  0.228205  0.143436  0.257088  0.769510  0.696590  0.033418  ...  0.362748        0.366324        0.359171 -0.000788       0.001364      -0.002941
7  0.922698  0.708231  0.491979  0.487305  0.653184  0.647319  ...  0.384214        0.387790        0.380638  0.002442       0.004594       0.000289
8  0.162086  0.053364  0.264185  0.847655  0.764146  0.251648  ...  0.429793        0.433369        0.426216 -0.000989       0.001164      -0.003141
9  0.699009  0.177936  0.887069  0.578979  0.993927  0.726453  ...  1.300269        1.303846        1.296693  0.003566       0.005719       0.001414

[10 rows x 15 columns]
```

**Comment by aaronkho** [comment]
Testing of additional functionality using 08853b4, after model loading from previous test:
```
In [5]: xtrain = model.training_inputs['GeTurb_1']

In [6]: ytrain = model.training_outputs['GeTurb_1']

In [7]: ymodel = model(xtrain, outputs=['GeTurb_1'])

In [8]: ymodel
Out[8]:
   GeTurb_1  GeTurb_1_upper  GeTurb_1_lower
0 -0.003808       -0.003067       -0.004550
1 -0.008071       -0.006624       -0.009517
2 -0.028628       -0.025796       -0.031459

In [9]: ytrain
Out[9]:
   GeTurb_1
0 -0.003808
1 -0.008071
2 -0.028628

In [10]: xscan = model.generateScan('GeTurb_1', iteration=-1, scan_range=0.5, scan_resolution=3)

In [11]: xscan
Out[11]:
        aLte      aLti      aLne
0   1.053077  1.045034  0.266717
1   1.579616  1.045034  0.266717
2   2.106155  1.045034  0.266717
3   2.632693  1.045034  0.266717
4   3.159232  1.045034  0.266717
5   2.106155  0.522517  0.266717
6   2.106155  0.783775  0.266717
7   2.106155  1.045034  0.266717
8   2.106155  1.306292  0.266717
9   2.106155  1.567551  0.266717
10  2.106155  1.045034  0.133358
11  2.106155  1.045034  0.200038
12  2.106155  1.045034  0.266717
13  2.106155  1.045034  0.333396
14  2.106155  1.045034  0.400075

In [12]: yscan = model(xscan, outputs=['GeTurb_1'])

In [13]: yscan
Out[13]:
    GeTurb_1  GeTurb_1_upper  GeTurb_1_lower
0  -0.007736       -0.004477       -0.010995
1  -0.018182       -0.014929       -0.021435
2  -0.028628       -0.025796       -0.031459
3  -0.039073       -0.035815       -0.042332
4  -0.049519       -0.046260       -0.052778
5  -0.204549       -0.201290       -0.207808
6  -0.116588       -0.113329       -0.119847
7  -0.028628       -0.025796       -0.031459
8   0.059333        0.062592        0.056074
9   0.147294        0.150553        0.144035
10  0.127707        0.130966        0.124448
11  0.049540        0.052789        0.046290
12 -0.028628       -0.025796       -0.031459
13 -0.106795       -0.103537       -0.110053
14 -0.184962       -0.181703       -0.188221
```

**Comment by pabloprf** [comment]
Testing this now. Is it ready to go @aaronkho ?

**Comment by pabloprf** [comment]
All works great. Beautiful capability @aaronkho. 
As soon as you give me the green light I'll merge.

**Comment by aaronkho** [comment]
Just waiting for Rachel to test on her own. Will let you know when that happens so we can merge.

**Comment by aaronkho** [comment]
Ready to merge @pabloprf

**Pull request merged**
