### PR TITLE
General bugfixes in preparation of SMARTS integration

### PR DESCRIPTION
**Pull request by aaronkho**
- Use Python built-in `issubclass()` function to check class definition object equality including possible inheritances (Note that Python built-in `isinstance()` function should be used for class instances)
- Remove calling of `printMsg()` when loading config file via `config_manager.set_config()`, which requires config file to already be set
- Added function `GACODE_PROFILES.toNumpyArrays()` to ensure all items in `GACODE_PROFILES.profiles` and `GACODE_PROFILES.derived` dictionaries are of type `numpy.ndarray`
- Added function `powerstate.to_cpu_tensors()` to ensure all items in `powerstate.plasma`, `powerstate.plasma_fine`, `powerstate.Xcurrent` and `powerstate.FluxMatch_Yopt` are moved to the CPU for downstream processing (This also calls `toNumpyArrays()` on `powerstate.profiles` if present)

### CODE REVIEW

**Comment by aaronkho** [comment]
Just in preparation of the `pathlib` work tomorrow, though I do not think these impact anyone's workflow except mine at the moment.

**Comment by pabloprf** [comment]
Yep, this all looks good and reasonable

**Comment by aaronkho** [comment]
Perfect, can I merge it to development then?

**Comment by pabloprf** [comment]
yes

**Comment by aaronkho** [comment]
Done. Thanks for the quick response!

**Pull request merged**
