### PR TITLE
Convert codebase over to pathlib

### PR DESCRIPTION
**Pull request by aaronkho**

### CODE REVIEW

**Comment by AudreySaltzman** [comment]
Update GACODErun.py and TGYROtools.py to use pathlib, now farming tools is updated.

**Comment by aaronkho** [comment]
Current functioning scripts: `TGLF_workflow.py`, `TGLFscan_workflow.py`, `TGYRO_workflow.py`, `OPT_workflow.py`, `TRANSP_workflow.py`, `FREEGS_workflow.py`, `CGYRO_workflow.py`.

`dill.pickler` issue was solved by ensuring `python < 3.13`. Keep an eye out because this may become an issue in the future if `dill` package does not catch it.

It should be noted that the workflow tests may not touch every logical branch within each file, so other workflows may still need further debugging. Also, the `globus` branch of the TRANSP application was not updated yet.

**Comment by pabloprf** [comment]
PORTALS workflow is also now good, and we realized we were doing keyword arguments equal to empty list throughout the code, which is bad practice and was making PORTALS workflow not work. Now it's fixed.
Removed EPED NN test because that requires private NN weights for now.

For next time, we should work on TRANSP globus

**Comment by pabloprf** [comment]
Given that PORTALS works next tests should be MAESTRO.

Also, don't forget non-tested capabilities. E.g. different ways to initialize TGLF? UFILES reader? input.gacode reader?

**Comment by pabloprf** [comment]
Note for future self: probably in this merge and new release we want to change the words `restart` and `restartYN` by something like `cold_restart`

**Comment by pabloprf** [comment]
Note to our future selves: This is NOT going to make Windows computers work... FARMINGtools rely on things like taring, and assumes also that folderExecution uses slashes.

**Comment by aaronkho** [comment]
Still waiting on MAESTRO test to finish, @AudreySaltzman .
Remaining lines only scrubbed on OPT, FREEGS, TGLF, TGYRO, partial in CYGRO. The other workflows have not been looked at in this detail yet.

**Comment by aaronkho** [comment]
`os.system("cp ...")` and `os.system("rm -r ...")` filesystem commands have no equivalent in `pathlib`, but will break in Windows OS. Recommended to look into using `shutil` for Windows compatibility for those operations.

`os.system("tar ...")` will fail for any Windows OS < 10.0.17063. However, this is not problematic since I do not think we need to support old Windows systems anyway.

**Comment by pabloprf** [comment]
After those fixes I just submitted, MAESTRO run until the end for me. I will keep testing other capabilities

**Comment by aaronkho** [comment]
Some remaining issues that I found:
- `FARMINGtools.py` hardcodes Linux-based commands into its SLURM submission scripts. Nothing can really be done about that, but I think it is more than reasonable to assume all remote systems are Linux. An issue would only come up if MITIM reuses these submission scripts when running locally.
- Some files use commands like `ssh` and `scp`. I did not touch these since I have no idea if that is Windows compatible or not.
- `correctNML()` in `IOtools.py` uses `tr` command to adjust for `\n\r` line breaks from Windows OS back to `\n` for Linux. No idea if this function gets used or not in the main workflows.
- `GEQtools.py` has a bunch of functions accepting filename arguments but does not explicitly convert them to `pathlib.Path`. I have left the functions assuming these are input as strings from now.

**Comment by pabloprf** [comment]
@aaronkho what did you intend to do here:
https://github.com/pabloprf/MITIM-fusion/blob/5c78a968eb7d0c7844dc2fc236ad3cc6ad3b8d10/src/mitim_modules/maestro/utils/PORTALSbeat.py#L123-L126

**Comment by aaronkho** [comment]
@pabloprf Yes I forgot to finish that change it seems. I was going to check whether the found folder contents were files or folders, in order to call the correct removal function for them. This has been fixed in my commit.

**Comment by pabloprf** [comment]
Thanks @aaronkho, all tests run fine in OSX now.

**Comment by pabloprf** [comment]
My last commits removed completely any other reference to ssh or scp, as mentioned in your comment https://github.com/pabloprf/MITIM-fusion/pull/36#issuecomment-2472041755

**Pull request merged**
