### PR TITLE
Auxiliary power can be provided manually and PORTALS surrogate reuse doesn't need training

### PR DESCRIPTION
**Pull request by pabloprf**

### CODE REVIEW

**Comment by pabloprf** [comment]
A note for myself before merging:
If we change the last roa, then we cannot do no-training flux-matching (which was originally implemented in this pull request). That's ok, but we need to change the logic to run a few iterations to get the last radii trained

**Comment by josephb-hall** [comment]
I'm in the process of testing the TRANSP updating of heating profiles, can you tell me what syntax you need to use to run it? The `transp_beat.finalize()` method isn't called anywhere that I can find. Should `self.finalize()` be called at the end of `transp_beat.run()`, or is there a different way you had in mind for doing this?

**Comment by pabloprf** [comment]
This is an example of how to run it. You must provide a function that shapes the heating profile and the total power:
```
from mitim_modules.maestro.MAESTROmain import maestro
from mitim_tools.misc_tools import PLASMAtools
from mitim_tools.misc_tools.IOtools import mitim_timer

folder = '/Users/pablorf/PROJECTS/project_2024_MAESTROexploration/'

# -----------------------------------------------------------------------------------------------------------------------
# Parameters
# -----------------------------------------------------------------------------------------------------------------------

case = 'd3d_run3'
parameters = {'Ip_MA': 1.15, 'B_T': 2.1, 'Zeff': 2.0, 'PichT_MW': 2.2}
parameters_mix = {'DTplasma': False, 'lowZ_impurity': 6.0}
geometry = {'R': 1.675, 'a': 0.67, 'kappa_sep': 1.8, 'delta_sep': 0.237, 'zeta_sep': 0.0, 'z0': 0.0}
parameters_bc = {'rhotop': 0.9, 'Ttop_keV': 0.6, 'netop_20': 0.3, 'Tsep_keV': 0.1, 'nesep_20': 0.1, 'BetaN': 1.0}
Pe_ratio = 0.4
BetaN_initialization = 1.0

# -----------------------------------------------------------------------------------------------------------------------
# Namelists
# -----------------------------------------------------------------------------------------------------------------------

# To see what values this namelist can take: mitim_tools/transp_tools/NMLtools.py: _default_params()
transp_namelist = {
    'flattop_window': 1.0,       # <--- To allow stationarity
    'dtEquilMax_ms': 10.0,       
    'dtHeating_ms' : 5.0,        
    'dtOut_ms' : 10.0,
    'dtIn_ms' : 10.0,
    'nzones' : 60,
    'nzones_energetic' : 20,    # Default but lower than what I used to use
    'nzones_distfun' : 10,      # Default but lower than what I used to use    
    'Pich': False, #parameters['PichT_MW']>0.0,
    'DTplasma': parameters_mix['DTplasma'],
    "zlump" :[ [parameters_mix['lowZ_impurity'], parameters_mix['lowZ_impurity']*2, 0.1] ],
    }

transp_namelist['coeffsSaw'] = [1.0,2.0,1.0,0.4]# vs [1.0,3.0,1.0,0.4]

# To see what values this namelist can take: mitim_modules/portals/PORTALSmain.py: __init__()
portals_namelist = {    
    "PORTALSparameters": {"launchEvaluationsAsSlurmJobs": True, 'use_tglf_scan_trick': 0.02},
    "MODELparameters": {
        "RoaLocations": [0.35,0.55,0.75,0.875,0.9],
        "transport_model": {"turbulence":'TGLF',"TGLFsettings": 6, "extraOptionsTGLF": {'USE_BPER':True}}},
    "INITparameters": {"FastIsThermal": True, "removeIons": [5,6], "quasineutrality": True},
    "exploration_ranges": {'ymax_rel': 1.0,'ymin_rel': 0.9,'hardGradientLimits': [None,2]}
    }

def P_auxiliary(rhotor):
    _, y = PLASMAtools.parabolicProfile(Tbar=1.0,nu=5.0,rho=rhotor,Tedge=0.0)
    return y
force_auxiliary_heating_at_output = {
    'Pe': [P_auxiliary, parameters['PichT_MW']*Pe_ratio],
    'Pi': [P_auxiliary, parameters['PichT_MW']*(1.0-Pe_ratio)],
    }

# -----------------------------------------------------------------------------------------------------------------------
# Workflow
# -----------------------------------------------------------------------------------------------------------------------

m = maestro(f'{folder}/{case}/', terminal_outputs = False)

@mitim_timer('\t\t* MAESTRO')
def run_maestro():
    # TRANSP
    m.define_beat('transp', initializer='freegs')
    m.define_creator('parameterization', **parameters_bc)
    m.initialize(**geometry, **parameters, BetaN = BetaN_initialization)
    m.prepare(**transp_namelist)
    m.run(force_auxiliary_heating_at_output = force_auxiliary_heating_at_output)

    # PORTALS
    m.define_beat('portals')
    m.prepare(**portals_namelist)
    m.run()

    # TRANSP
    m.define_beat('transp')
    m.prepare(**transp_namelist)
    m.run(force_auxiliary_heating_at_output = force_auxiliary_heating_at_output)

    # PORTALS
    m.define_beat('portals')
    m.prepare(**portals_namelist)
    m.run()

    m.finalize()

    return m

m = run_maestro()   
```

**Comment by josephb-hall** [comment]
Merging, this looks like it's ready to start testing on engaging?

**Pull request merged**
